### ISSUE TITLE
todo: support for negative preconditions

### ISSUE THREAD

**Issue by guicho271828** [aibasel/pyperplan#8]

**Comment by maltehelmert** [comment]
Hi Masataro, I think we would be unlikely to implement this. Pyperplan deliberately only support STRIPS to keep the code simple. If were to extend the code, I would prefer extending it to full ADL rather than just negative preconditions, since I think this would involve some interesting didactical concepts. But I don't think we have the resources for this. Maybe you want to add negative preconditions in a fork?

**Comment by guicho271828** [comment]
I see, did not know the intended scope was STRIPS.

**Comment by karolyartur** [comment]
Hi!

@maltehelmert 
I see, that you were considering extending the code to support full ADL. Is there any progress made in this direction?
If not, do you know of any similar approach, that uses Python and also support ADL?
I would be glad if you could point me in the right direction.

**Comment by maltehelmert** [comment]
There is currently no active development of pyperplan. It is primarily a teaching tool, and our development work is focused more on research. Our "serious" planner, Fast Downward, supports ADL, but is (primarily) implemented in C++. We eventually plan to make it easier to interface Fast Downward with Python, via a Python library interface. Perhaps this could serve your use case. But this is more of a long-term plan, unfortunately.

**Comment by karolyartur** [comment]
Thank you!
At this point Fast Downward seems to be the only option.
